DROP SCHEMA PUBLIC CASCADE;
CREATE SCHEMA PUBLIC;

CREATE TABLE account (
  id BIGSERIAL PRIMARY KEY,
  license VARCHAR(36) UNIQUE NOT NULL,
  email_address VARCHAR UNIQUE NOT NULL,
  pin VARCHAR(7) NOT NULL,
  activated BIGINT NOT NULL,
  deactivated BIGINT NOT NULL
);

CREATE TABLE swimmer (
  id BIGSERIAL PRIMARY KEY,
  swimmer_id BIGINT REFERENCES account(id),
  name VARCHAR(24) NOT NULL,
  swam BIGINT NOT NULL
);